models:
  - type: main
    engine: nvidia
    model: meta/llama-3.1-8b-instruct

instructions:
  - type: general
    content: |
      You are a helpful assistant that answers questions about hardware modules only.

sample_conversation: |
  user "Hello!"
    express greeting
  bot express greeting

rails:
  input:
    flows:
      - politics check
      - sensitive info check
